name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup compiler
      run: apt-get install -y gcc-9 libtbb-dev
    - name: make
      run: make cg CLASS=S
