name: Build and run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mgnisia/nas_ubuntu
    strategy:
      matrix:
        kernels: [cg, ep, ft, mg, is]
    steps:
    - uses: actions/checkout@v2
    - name: make ${{ matrix.kernels }}
      run: make ${{ matrix.kernels }} CLASS=S
    - name: run ${{ matrix.kernels }}
      run: ./bin/${{ matrix.kernels }}.S
