name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Ubuntu Contaier build
        uses: outillage/kaniko-action@master
        with:
          image: mgnisia/nas_ubuntu
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: true
          build_file: Docker/Ubuntu.Dockerfile
          cache_registry: mgnisia/cache
      - name: Arch build build
        uses: outillage/kaniko-action@master
        with:
          image: mgnisia/nas_arch
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: true
          build_file: Docker/Arch.Dockerfile
          cache_registry: mgnisia/cache