name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: mgnisia/pstl_npb@master
    # Use the output from the `hello` step
    - name: Compile Conjugate gradient
      run: make cg CLASS=S